import { PageIntro } from "@/components/page-intro";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { getSession } from "@/lib/session";

export const TERMS_LAST_UPDATED = "2026-09-18";
export const SUPPORT_EMAIL = "support@example.com";

export const TERMS_SECTIONS = [
  "Eligibility and age",
  "Service description",
  "AI-generated content",
  "Acceptable use and prohibited content",
  "Moderation and enforcement",
  "Subscriptions, billing, and refunds",
  "Cancellation",
  "Account termination",
  "Disclaimers",
  "Changes to these terms",
  "Contact",
] as const;

export default async function TermsPage() {
  const session = await getSession();
  return (
    <div className="flex min-h-full flex-col">
      <SiteHeader signedIn={Boolean(session)} />
      <main className="mx-auto flex w-full max-w-2xl flex-1 flex-col gap-8 px-4 py-12">
        <PageIntro eyebrow="Terms of Service" title="Fembo Terms of Service">
          <p>
            Last updated: {TERMS_LAST_UPDATED}. By creating an account or using Fembo, you agree to
            these Terms. Fembo is a general-audience (16+) AI companion service.
          </p>
        </PageIntro>

        <div className="flex flex-col gap-8 text-sm leading-7 text-muted-foreground">
          <section>
            <h2 className="mb-2 font-medium text-foreground">1. Eligibility and age</h2>
            <p>
              You must be at least 16 years old to use Fembo. By registering, you confirm your date
              of birth and that you meet this requirement. We may suspend or terminate accounts that
              do not meet age requirements or that we reasonably believe are used by minors.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-medium text-foreground">2. Service description</h2>
            <p>
              Fembo provides private AI companion conversations, optional visual and voice modes,
              memories, and related features. Fembo is entertainment software. It is not therapy,
              medical advice, legal advice, or a substitute for human support in a crisis. If you are
              in immediate danger, contact local emergency services.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-medium text-foreground">3. AI-generated content</h2>
            <p>
              Companion replies are generated by third-party AI models routed through our inference
              provider (currently OpenRouter). Outputs may be inaccurate, inconsistent, or
              inappropriate despite safety controls. You are responsible for how you use generated
              content. Do not rely on Fembo for decisions that require professional judgment.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-medium text-foreground">
              4. Acceptable use and prohibited content
            </h2>
            <p>You may not use Fembo to create, request, store, or distribute content that:</p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              <li>Involves minors, age-play, or sexual content of any kind</li>
              <li>Depicts or promotes non-consensual sexual activity</li>
              <li>Is illegal in your jurisdiction or violates applicable law</li>
              <li>Impersonates real people without consent or facilitates harassment</li>
              <li>Provides instructions for self-harm, violence, or terrorism</li>
              <li>Attempts to bypass safety, moderation, or billing controls</li>
            </ul>
            <p className="mt-2">
              Fembo is SFW only. Explicit sexual content is not permitted on the platform.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-medium text-foreground">5. Moderation and enforcement</h2>
            <p>
              We apply automated checks before and after model responses and review user reports.
              Violations may result in content removal, feature restrictions, account suspension, or
              permanent termination. We maintain an internal incident queue for audit and escalation.
              We may cooperate with payment processors and lawful requests when required.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-medium text-foreground">
              6. Subscriptions, billing, and refunds
            </h2>
            <p>
              Fembo Plus is a recurring subscription billed through our payment processor. Current
              pricing is shown at checkout. Payments are processed by Stripe (or, when approved for
              your region, an adult billing processor such as CCBill or Segpay). Processor names and
              descriptors may appear on your bank statement.
            </p>
            <p className="mt-2">
              Except where required by law, subscription fees are non-refundable once a billing
              period has started. If you believe you were charged in error, contact{" "}
              <a href={`mailto:${SUPPORT_EMAIL}`} className="underline">
                {SUPPORT_EMAIL}
              </a>{" "}
              within 14 days with your account email and transaction details.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-medium text-foreground">7. Cancellation</h2>
            <p>
              You may cancel Plus at any time from Settings or the billing portal linked on the Plus
              page. Cancellation stops future renewals; access continues until the end of the current
              paid period unless otherwise stated at checkout. Deleting your account does not
              automatically cancel an active subscription—cancel billing first.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-medium text-foreground">8. Account termination</h2>
            <p>
              You may export your data and delete your account from Settings. We may suspend or
              terminate access for violations of these Terms, suspected fraud, chargebacks, or
              operational necessity. Upon termination, your right to use Fembo ends immediately except
              where retention is required by law or payment dispute rules.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-medium text-foreground">9. Disclaimers</h2>
            <p>
              Fembo is provided &quot;as is&quot; without warranties of any kind. We do not guarantee
              uninterrupted availability, error-free AI output, or preservation of every message. Export
              your data periodically; you are responsible for backups you need.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-medium text-foreground">10. Changes to these terms</h2>
            <p>
              We may update these Terms. Material changes will be reflected by updating the date
              above. Continued use after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="mb-2 font-medium text-foreground">11. Contact</h2>
            <p>
              Questions about these Terms or billing:{" "}
              <a href={`mailto:${SUPPORT_EMAIL}`} className="underline">
                {SUPPORT_EMAIL}
              </a>
              . Abuse or safety reports may also be submitted via in-app reporting or the abuse form
              on our site.
            </p>
          </section>
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}
